#!/usr/bin/env bash
# 🚀 QUICK START - Multiplayer Blackhole 1+2+3

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎮 BLACKHOLE - MULTIPLAYER QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 CHECKLIST AVANT DE TESTER${NC}"
echo ""
echo "✅ Fichiers créés:"
echo "   • frontend/src/routes/menu/multiplayer_selector.js (300 lignes)"
echo "   • frontend/src/routes/ingame/game-state-sync.js (400 lignes)"
echo ""
echo "✅ Fichiers modifiés:"
echo "   • frontend/src/routes/menu/menu.js (+40 lignes)"
echo "   • frontend/src/routes/menu/menu.html (+1 ligne)"
echo "   • frontend/src/routes/menu/menu.css (+240 lignes)"
echo "   • backend/python/app/api/routes/matchmaking.py (+50 lignes)"
echo "   • backend/python/app/api/routes/rooms.py (+40 lignes)"
echo ""
echo "✅ Documentation:"
echo "   • MULTIPLAYER_INTEGRATION_GUIDE.md (guide complet)"
echo "   • MULTIPLAYER_DEPLOYMENT.md (déploiement + tests)"
echo "   • MULTIPLAYER_CHECKLIST.md (80+ items)"
echo "   • IMPLEMENTATION_STATUS.md (statut)"
echo ""

echo -e "${BLUE}🚀 DÉMARRER LES SERVICES${NC}"
echo ""
echo "Terminal 1 - Backend:"
echo "   cd backend/python"
echo "   python -m uvicorn app.main:app --reload"
echo ""
echo "Terminal 2 - Frontend:"
echo "   cd frontend"
echo "   npm run dev"
echo ""

echo -e "${BLUE}🧪 TEST MODE RAPIDE (Auto-matchmaking)${NC}"
echo ""
echo "1. Ouvre 2 navigateurs:"
echo "   Browser 1: http://localhost:5173"
echo "   Browser 2: http://localhost:5173"
echo ""
echo "2. Browser 1:"
echo "   Menu → [MULTIJOUEUR]"
echo "   Mode Rapide → [Commencer]"
echo "   → Attendre l'autre joueur..."
echo ""
echo "3. Browser 2:"
echo "   Menu → [MULTIJOUEUR]"
echo "   Mode Rapide → [Commencer]"
echo "   → Match trouvé!"
echo ""
echo "4. Résultat attendu:"
echo "   ✓ Les 2 redirigés vers: /ingame?mp=1&difficulty=X&stage=Y&seed=ABC123"
echo "   ✓ Même URL = même maze (propriété seeded!)"
echo ""

echo -e "${BLUE}🧪 TEST MODE PRIVÉ (Room avec code)${NC}"
echo ""
echo "1. Browser 1:"
echo "   Menu → [MULTIJOUEUR]"
echo "   Mode Privé → [Créer une room]"
echo "   → Reçoit: \"Code: ABC123\""
echo ""
echo "2. Browser 2:"
echo "   Menu → [MULTIJOUEUR]"
echo "   Mode Privé → Tab \"Rejoindre\""
echo "   Input: ABC123"
echo "   → [Rejoindre]"
echo ""
echo "3. Résultat attendu:"
echo "   ✓ Tous les 2 dans: /ingame?mp=1&...&room=ABC123"
echo "   ✓ Même seed généré par backend"
echo ""

echo -e "${BLUE}🧪 TEST AUTO-MATCHMAKING TOGGLE${NC}"
echo ""
echo "1. Menu → [MULTIJOUEUR]"
echo "2. Mode Rapide → Toggle ON"
echo "   \"🔘 Auto-matchmaking à chaque connexion\""
echo "3. Reload page"
echo "4. Résultat attendu:"
echo "   ✓ Clique [MULTIJOUEUR] = direct /ingame (pas de modal!)"
echo ""

echo -e "${BLUE}📊 ENDPOINTS À TESTER${NC}"
echo ""
echo "Mode Rapide (Matchmaking):"
echo "   POST http://localhost:8000/api/matchmaking/join"
echo "   Query: ?difficulty=facile&stage=15"
echo "   Header: Cookie: session=YOUR_SESSION"
echo ""
echo "Mode Privé (Room):"
echo "   POST http://localhost:8000/api/rooms"
echo "   Query: ?difficulty=facile&stage=15"
echo "   Header: Cookie: session=YOUR_SESSION"
echo ""

echo -e "${BLUE}📖 DOCUMENTATION${NC}"
echo ""
echo "Fichiers clés:"
echo "   📍 MULTIPLAYER_SUMMARY.md - Vue d'ensemble"
echo "   📍 MULTIPLAYER_DEPLOYMENT.md - Guide déploiement"
echo "   📍 MULTIPLAYER_INTEGRATION_GUIDE.md - Tous les détails"
echo "   📍 IMPLEMENTATION_STATUS.md - Statut 1+2+3"
echo ""

echo -e "${YELLOW}⏳ PROCHAINE ÉTAPE (URGENT)${NC}"
echo ""
echo "Intégration IngameView (Niveau 3):"
echo "   1. Parser query params (mp, difficulty, stage, seed, room)"
echo "   2. Importer GameStateSync"
echo "   3. Initialiser SeededMazeGenerator(width, height, seed)"
echo "   4. Rendre opponent sur le terrain"
echo "   5. Gérer victoire/défaite multijoueur"
echo ""
echo "Code exemple dans:"
echo "   → game-state-sync.js (fin du fichier)"
echo "   → MULTIPLAYER_INTEGRATION_GUIDE.md (section finale)"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ STATUT: 80% Complété (Niveaux 1+2+3 done, IngameView pending)${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "🎮 Bon test!"
echo ""
